Type: AWS::CloudFront::Distribution
Properties:
  DistributionConfig:
    Enabled: true
    HttpVersion: http2and3
    # Aliases: - custom domain
    #   - ${param:DOMAIN_ALIASES}
    PriceClass: PriceClass_100
    WebACLId: ${param:AWS_CLOUDFRONT_WAF_ARN}
    Origins:
      - Id: ServerOrigin
        DomainName:
          # The !GetAtt returns a full URL like "https://abcdef.lambda-url.region.on.aws/"
          # We need to split it by "/" and select the 3rd element (index 2)
          Fn::Select:
            - 2
            - Fn::Split:
                - "/"
                - Fn::GetAtt: ServerLambdaFunctionUrl.FunctionUrl
        CustomOriginConfig:
          OriginProtocolPolicy: https-only
          OriginKeepaliveTimeout: 5
          OriginReadTimeout: 115
      - Id: S3Origin
        DomainName:
          Fn::Join:
            - "."
            - - Ref: Bucket
              - s3
              - Ref: AWS::Region
              - Ref: AWS::URLSuffix
        OriginAccessControlId:
          Ref: OriginAccessControl
        S3OriginConfig:
          OriginAccessIdentity: ""

    # default to lambda
    DefaultCacheBehavior:
      TargetOriginId: ServerOrigin
      ViewerProtocolPolicy: redirect-to-https
      CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
      OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewer
      
    # statics
    CacheBehaviors:
      - PathPattern: /_next/static/*
        TargetOriginId: S3Origin
        ViewerProtocolPolicy: redirect-to-https
        CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
        Compress: true
      - PathPattern: /static/*
        TargetOriginId: S3Origin
        ViewerProtocolPolicy: redirect-to-https
        CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
        Compress: true

    CustomErrorResponses:
      - ErrorCode: 400
        ResponsePagePath: /400
        ResponseCode: 400
        ErrorCachingMinTTL: 300
      - ErrorCode: 403
        ResponsePagePath: /403
        ResponseCode: 403
        ErrorCachingMinTTL: 300
      - ErrorCode: 404
        ResponsePagePath: /404
        ResponseCode: 404
        ErrorCachingMinTTL: 300
      - ErrorCode: 500
        ResponsePagePath: /500
        ResponseCode: 500
        ErrorCachingMinTTL: 300
    # ViewerCertificate: - custom domain
    #   AcmCertificateArn: ${param:AWS_ACM_CERTIFICATION_ARN}
    #   SslSupportMethod: sni-only
    #   MinimumProtocolVersion: TLSv1.2_2021
