name: push

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ENVIRONMENT: develop
  AWS_REGION: ap-northeast-1

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: npm ci
        run: npm ci

      - name: build
        run: npm run build
        env:
          CI: false
